- gz_topic_name: "/clock"
  ros_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: "GZ_TO_ROS"
- gz_topic_name: "/camera_1/camera_info"
  ros_topic_name: "/camera_1/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"
- gz_topic_name: "/camera_1/image_raw"
  ros_topic_name: "/camera_1/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"
- gz_topic_name: "/camera_2/camera_info"
  ros_topic_name: "/camera_2/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"
- gz_topic_name: "/camera_2/image_raw"
  ros_topic_name: "/camera_2/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"
- gz_topic_name: "/camera_3/camera_info"
  ros_topic_name: "/camera_3/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"
- gz_topic_name: "/camera_3/image_raw"
  ros_topic_name: "/camera_3/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"
- gz_topic_name: "/depth_camera/camera_info"
  ros_topic_name: "/depth_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"
- gz_topic_name: "/depth_camera/depth_image"
  ros_topic_name: "/depth_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"
- gz_topic_name: "/depth_camera/depth_image/points"
  ros_topic_name: "/depth_camera/depth_image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: "GZ_TO_ROS"
